name: Actions CI

on:
  push:
    branches:
    - master
    paths: 
      - '**'
      - '!.editorconfig'
      - '!.gitattributes'
      - '!.gitignore'
      - '!*.md'
      - '!LICENSE'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  CONFIGURATION: 'Release'
  VERBOSITY:  'Minimal'

jobs: 
  Build:
    name: Build on ${{ matrix.dotnet }}    
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        dotnet: ['3.1.100']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Extract build and copyright information into variables
      id: info
      run: |
        echo "##[set-output name=build;]$(echo prebuild.$(git rev-list --count HEAD))"
        echo "##[set-output name=copyright;]$(echo © $(date -u +%Y) Bytewizer.  All rights reserved.)"

    - name: Show build information
      run: |
        echo build=${{ steps.info.outputs.build }}
        echo copyright=${{ steps.info.outputs.copyright }}

    - name: Setup dotnet (${{ matrix.dotnet }})
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
      
    - name: Display dotnet (${{ matrix.dotnet }})
      run: dotnet --info
    
    - name: Restore dotnet (${{ matrix.dotnet }})
      run: dotnet restore --verbosity ${VERBOSITY}
    
    - name: Build dotnet (${{ matrix.dotnet }})
      run: >-
        dotnet build -p:Copyright="${{ steps.info.outputs.copyright }}"
        --version-suffix ${{ steps.info.outputs.build }}
        --no-restore
        --verbosity ${VERBOSITY}
        --configuration ${CONFIGURATION} 
      
    - name: Test dotnet (${{ matrix.dotnet }})
      run: >-
        dotnet test
        --no-restore 
        --no-build 
        --verbosity ${VERBOSITY} 
        --configuration ${CONFIGURATION} 
        --results-directory .builds/artifacts 
        --logger:trx
      env:
        Agent__ApplicationKey: ${{ secrets.AGENT_APPLICATION_KEY }}
        Agent__KeyId: ${{ secrets.AGENT_KEY_ID }}
        
    - name: Pack dotnet (${{ matrix.dotnet }})
      run: >- 
        dotnet pack -p:Copyright="${{ steps.info.outputs.copyright }}"
        --version-suffix ${{ steps.info.outputs.build }}
        --include-symbols 
        --no-restore 
        --no-build 
        --verbosity ${VERBOSITY} 
        --configuration ${CONFIGURATION} 
        --output .builds/artifacts
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Build
        path: .builds/artifacts