name: Actions CI

on:
  push:
    branches:
    - master
    paths: 
      - '**'
      - '!.editorconfig'
      - '!.gitattributes'
      - '!.gitignore'
      - '!*.md'
      - '!LICENSE'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  CONFIGURATION: 'Release'
  VERBOSITY:  'Minimal'

jobs: 
  Build:
    name: Build on ${{ matrix.dotnet }}    
    runs-on: [windows-latest]
    strategy:
      matrix:
        dotnet: ['3.1.100']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Extract build and copyright information into variables
      id: info
      run: |
        echo "##[set-output name=build;]$(echo $(git rev-list --count HEAD))"
        echo "##[set-output name=copyright;]$(echo © $(date -u +%Y) Bytewizer.  All rights reserved.)"

    - name: Show build information
      run: |
        echo build=${{ steps.info.outputs.build }}
        echo copyright=${{ steps.info.outputs.copyright }}

    - name: Setup dotnet (${{ matrix.dotnet }})
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
      
    - name: Display dotnet (${{ matrix.dotnet }})
      run: dotnet --info
                
    - name: Pack libraries (${{ matrix.dotnet }})
      working-directory: ./src
      run: >- 
        dotnet pack Bytewizer.TinyCLR.Microserver.sln -p:BuildNumber="${{ steps.info.outputs.build }}" -p:Copyright="${{ steps.info.outputs.copyright }}"
        --version-suffix prebuild.${{ steps.info.outputs.build }}
        --include-symbols 
        --verbosity ${env:VERBOSITY} 
        --configuration ${env:CONFIGURATION} 
        --output /builds/artifacts
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Build
        path: /builds/artifacts
